RFC5646_redundant= {
    'az-Arab':'Azerbaijani in Arabic script. ',
    'az-Cyrl':'Azerbaijani in Cyrillic script. ',
    'az-Latn':'Azerbaijani in Latin script. ',
    'be-Latn':'Belarusian in Latin script. ',
    'bs-Cyrl':'Bosnian in Cyrillic script. ',
    'bs-Latn':'Bosnian in Latin script. ',
    'de-1901':'German, traditional orthography. ',
    'de-1996':'German, orthography of 1996. ',
    'de-AT-1901':'German, Austrian variant, traditional orthography. ',
    'de-AT-1996':'German, Austrian variant, orthography of 1996. ',
    'de-CH-1901':'German, Swiss variant, traditional orthography. ',
    'de-CH-1996':'German, Swiss variant, orthography of 1996. ',
    'de-DE-1901':'German, German variant, traditional orthography. ',
    'de-DE-1996':'German, German variant, orthography of 1996. ',
    'en-boont':'Boontling. ',
    'en-scouse':'Scouse. ',
    'es-419':'Latin American Spanish. ',
    'iu-Cans':'Inuktitut in Canadian Aboriginal Syllabic script. ',
    'iu-Latn':'Inuktitut in Latin script. ',
    'mn-Cyrl':'Mongolian in Cyrillic script. ',
    'mn-Mong':'Mongolian in Mongolian script. ',
    'sgn-BR':'Brazilian Sign Language. ',
    'sgn-CO':'Colombian Sign Language. ',
    'sgn-DE':'German Sign Language. ',
    'sgn-DK':'Danish Sign Language. ',
    'sgn-ES':'Spanish Sign Language. ',
    'sgn-FR':'French Sign Language. ',
    'sgn-GB':'British Sign Language. ',
    'sgn-GR':'Greek Sign Language. ',
    'sgn-IE':'Irish Sign Language. ',
    'sgn-IT':'Italian Sign Language. ',
    'sgn-JP':'Japanese Sign Language. ',
    'sgn-MX':'Mexican Sign Language. ',
    'sgn-NI':'Nicaraguan Sign Language. ',
    'sgn-NL':'Dutch Sign Language. ',
    'sgn-NO':'Norwegian Sign Language. ',
    'sgn-PT':'Portuguese Sign Language. ',
    'sgn-SE':'Swedish Sign Language. ',
    'sgn-US':'American Sign Language. ',
    'sgn-ZA':'South African Sign Language. ',
    'sl-nedis':'Natisone dialect, Nadiza dialect. ',
    'sl-rozaj':'Resian, Resianic, Rezijan. ',
    'sr-Cyrl':'Serbian in Cyrillic script. ',
    'sr-Latn':'Serbian in Latin script. ',
    'tg-Arab':'Tajik in Arabic script. ',
    'tg-Cyrl':'Tajik in Cyrillic script. ',
    'uz-Cyrl':'Uzbek in Cyrillic script. ',
    'uz-Latn':'Uzbek in Latin script. ',
    'yi-Latn':'Yiddish, in Latin script. ',
    'zh-cmn':'Mandarin Chinese. ',
    'zh-cmn-Hans':'Mandarin Chinese (Simplified). ',
    'zh-cmn-Hant':'Mandarin Chinese (Traditional). ',
    'zh-gan':'Kan or Gan. ',
    'zh-Hans':'simplified Chinese. ',
    'zh-Hans-CN':'PRC Mainland Chinese in simplified script. ',
    'zh-Hans-HK':'Hong Kong Chinese in simplified script. ',
    'zh-Hans-MO':'Macao Chinese in simplified script. ',
    'zh-Hans-SG':'Singapore Chinese in simplified script. ',
    'zh-Hans-TW':'Taiwan Chinese in simplified script. ',
    'zh-Hant':'traditional Chinese. ',
    'zh-Hant-CN':'PRC Mainland Chinese in traditional script. ',
    'zh-Hant-HK':'Hong Kong Chinese in traditional script. ',
    'zh-Hant-MO':'Macao Chinese in traditional script. ',
    'zh-Hant-SG':'Singapore Chinese in traditional script. ',
    'zh-Hant-TW':'Taiwan Chinese in traditional script. ',
    'zh-wuu':'Shanghaiese or Wu. ',
}
