RFC5646_grandfathered= {
    'art-lojban':'Lojban. ',
    'cel-gaulish':'Gaulish. ',
    'en-GB-oed':'English, Oxford English Dictionary spelling. ',
    'i-ami':'Amis. ',
    'i-bnn':'Bunun. ',
    'i-default':'Default Language. ',
    'i-enochian':'Enochian. ',
    'i-hak':'Hakka. ',
    'i-klingon':'Klingon. ',
    'i-lux':'Luxembourgish. ',
    'i-mingo':'Mingo. ',
    'i-navajo':'Navajo. ',
    'i-pwn':'Paiwan. ',
    'i-tao':'Tao. ',
    'i-tay':'Tayal. ',
    'i-tsu':'Tsou. ',
    'no-bok':'Norwegian Bokmal. ',
    'no-nyn':'Norwegian Nynorsk. ',
    'sgn-BE-FR':'Belgian-French Sign Language. ',
    'sgn-BE-NL':'Belgian-Flemish Sign Language. ',
    'sgn-CH-DE':'Swiss German Sign Language. ',
    'zh-guoyu':'Mandarin or Standard Chinese. ',
    'zh-hakka':'Hakka. ',
    'zh-min':'Min, Fuzhou, Hokkien, Amoy, or Taiwanese. ',
    'zh-min-nan':'Minnan, Hokkien, Amoy, Taiwanese, Southern Min, Southern. ',
    'zh-xiang':'Xiang or Hunanese. ',
}
